### ISSUE TITLE
ln: failed to create symbolic link '/usr/share/sip/PyQt5/.': No such file or directory

### ISSUE THREAD

**Issue by KenwoodFox** [m2-farzan/ros2-foxy-PKGBUILD#9]
Not used to diagnosing too many strange errors like this but, when building i get the ln error, i checked i do have sip and pyqt5 and that dir exists but.. whats with the trailing dot after PyQt5? i may just be unused to using `ln` but im not familer with that syntax

Anyway, id be more than happy to check some system configuration options and or put a pr together if theres missing deps or anything!

```
ln: failed to create symbolic link '/usr/share/sip/PyQt5/.': No such file or directory
==> ERROR: A failure occurred in prepare().
    Aborting...
error: failed to build 'ros2-foxy-2020.12.11-5': 
error: packages failed to build: ros2-foxy-2020.12.11-5
```

**Comment by m2-farzan** [comment]
Hi

Thanks for reporting the issue. I'll fix it in a few minutes.

P.S. I strongly recommend galactic over foxy. The nature of Arch makes it difficult to maintain older versions. Even galactic package has [3 open issues](https://github.com/m2-farzan/ros2-galactic-PKGBUILD/issues), and currently requires minor manual interventions (read the issues for more info).

If you really need foxy on Arch, you can still use this package but you'll probably encounter more errors along the way. You can get ideas from [galactic](https://github.com/m2-farzan/ros2-galactic-PKGBUILD/commits/master) which is 10+ commits ahead of this one. In that case, I'd be very happy to merge your PR's into foxy package.

**Comment by m2-farzan** [comment]
The issue should be fixed now.

**Comment by KenwoodFox** [comment]
Looks like its still broken on manjaro and arch pure, but ill try galactic thank you
